### ISSUE TITLE
iPhone XR 16.6.1 stuck at 10% then crashes and sometimes kernel panics

### ISSUE THREAD

**Issue by Panky55** [mineek/Serotonin#15]
Title

**Comment by Panky55** [comment]
I managed to get it to work but after the user space reboot there is no text at the bottom of the Lock Screen and the tweaks don’t work

**Comment by moayad9458** [comment]
How

**Comment by Panky55** [comment]
I think it’s an issue with ldid I can see errors

**Comment by Panky55** [comment]
![IMG_0059](https://github.com/mineek/Serotonin/assets/66234114/b5153c62-5acd-4b6a-981d-da88e07e21a8)
![IMG_0058](https://github.com/mineek/Serotonin/assets/66234114/687fd309-0727-4195-b242-de1e48fd078d)

**Comment by Panky55** [comment]
It finally worked after a few more tries but please improve the stability
