### ISSUE TITLE
Serotonin 1.1.0 kernel panicking on my m1 ipad pro.

### ISSUE THREAD

**Issue by DownBeatGnu7882** [mineek/Serotonin#17]
I pressed jelbrek and it kernel panicked.
Here is the ips file of the kernel panic: [panic-full-2024-01-08-121734.000.txt](https://github.com/mineek/Serotonin/files/13866017/panic-full-2024-01-08-121734.000.txt)

**Comment by jrapf32** [comment]
Just keep trying until the Bootstrap app stays Bootstrapped then hit respring.
