### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by whoeevee** [mineek/Serotonin#18]
iPhone 13, iOS 16.2

After clicking "Jelbrek", it successfully completes with "launchd haxed". However, upon userspace reboot, only a userspace reboot occurs without the Springboard being hooked. No panics or crashes, it's simply not working.

**Comment by Adrian-1994** [comment]
Having the same issue on 16.2, iPhone 14. Doesn’t crash, just doesn’t work at all.

**Comment by Moheatt** [comment]
Same for me

**Comment by 333gn** [comment]
same for me

**Comment by whoeevee** [comment]
Serotonin is now working for me with this build!
#27 (comment)
Anyone else who experienced similar issues like the above, use this build from haxi0!

**Comment by whoeevee** [comment]
Serotonin is now working for me with this build!
#27
Anyone else who experienced similar issues like the above, use this build from haxi0!
