### ISSUE TITLE
doesn't work on 16.3

### ISSUE THREAD

**Issue by trevor425** [mineek/Serotonin#22]
its still doesnt work on ios 16.3 iphone 11

**Comment by D4D25A** [comment]
Same here. iPhone 14 Pro 16.3. Got it working with haxi0’s build instead: https://raw.githubusercontent.com/haxi0/Serotonin/A12restart/Serotonin.tipa

Perhaps libpatchfinder is causing this? Haxi0’s version has hardcoded offsets instead.

**Comment by trevor425** [comment]
thanks dude it does work now
