### ISSUE TITLE
Notchless/Dynamic Islandless Device support

### ISSUE THREAD

**Issue by RazaviIoz** [mineek/Serotonin#23]
Will serotonin ever support Iphone 6s-8 / Iphone SE 3 in the future?

**Comment by D4D25A** [comment]
Pretty sure SE 3 is supported. I don’t see why it wouldn’t be.

**Comment by RazaviIoz** [comment]
> Pretty sure SE 3 is supported. I don’t see why it wouldn’t be.

I've tried many times but I'm don't know if it worked even when it does let me user space reboot cuz I don't get the footnote on my ui

**Comment by D4D25A** [comment]
What iOS version is your SE 3 on? Maybe try the build I linked in the issue I opened, I was experiencing the same thing: https://github.com/mineek/Serotonin/issues/27

**Comment by RazaviIoz** [comment]
> What iOS version is your SE 3 on? Maybe try the build I linked in the issue I opened, I was experiencing the same thing: #27
> 
> If that build works for you please comment +1 on the issue I linked.

Thank you it worked!!!!!!
