### ISSUE TITLE
you have no zsh startup files

### ISSUE THREAD

**Issue by asfxdi0** [mineek/Serotonin#31]
![262386c6-0ca3-456d-b91d-f99ef2bb2e24](https://github.com/mineek/Serotonin/assets/91019559/7d86e4fd-c18c-4364-b014-e42ec14a3433)

when I want to install .deb via filza it says you have no zsh startup files

**Comment by dleovl** [comment]
Install `.deb` files through Sileo. All this is saying is that `pkg` doesn't exist as a command.

**Comment by asfxdi0** [comment]
> Install `.deb` files through Sileo. All this is saying is that `pkg` doesn't exist as a command.


I haven't found a single guide on the Internet on how to do this...

**Comment by dleovl** [comment]
> > Install `.deb` files through Sileo. All this is saying is that `pkg` doesn't exist as a command.
> 
> I haven't found a single guide on the Internet on how to do this...

Share the `.deb` with Sileo/Patcher
