### ISSUE TITLE
Offset Finder gets the wrong base address for M2 16.4.1 iPad Pro

### ISSUE THREAD

**Issue by lilmayofuksu** [mineek/Serotonin#48]
Obviously it always fails no matter the puaf method/page/headroom size.
Manually replacing the base address in offsets.txt with the correct one fixes the boot panic.

**Comment by priom96** [comment]
How do you find your base address, I’m on IOS 16.5 iPad mini 6th gen. Also once you update the .txt how do you recompile the ipa. Thanks

**Comment by lilmayofuksu** [comment]
Fixed with https://github.com/mineek/Serotonin/commit/091fe0b13d0b97fd06f3703f4688a54754485205
