### ISSUE TITLE
iPad Air M1 (1.2.0 installed) doesn’t launch on iOS 16.5

### ISSUE THREAD

**Issue by 4193883-eng** [mineek/Serotonin#60]
https://github.com/mineek/Serotonin/assets/83756034/395f643a-a4ab-41af-b16a-b8d90bdd7c47

Can’t even go into the app. I have tried to use this on version 1.1.0, but it kernel panicked. And now it doesn’t even launch, so I can’t change any settings in the app.
I have reinstalled it multiple times through TS

**Comment by ricosuave0922** [comment]
If you have a Magic Keyboard, make sure that is detached/disconnected. App insta crashes for me when it’s connected but launches and jailbreaks just fine when it isn’t.

**Comment by TheOneWhoIsCool** [comment]
is your trollstore latest?

**Comment by jonahnm** [comment]
Use 1.2.0

**Comment by Carmen-Carmen** [comment]
You should disconnect Magic Keyboard. It also causes Serotonin on my iPad pro M1 to crash.
BTW, what is the terminal App on your home screen? How to enable it?
THX~

**Comment by 4193883-eng** [comment]
solved, disconnected the keyboard
