### ISSUE TITLE
The app just crashes when I try to launch it

### ISSUE THREAD

**Issue by KernelFox0** [mineek/Serotonin#85]
On latest bootstrap, tried deleting and reinstalling it and deleting every serotonin related file from /var

It worked once perfectly, then I had to restart the device, it panicked, and now it’s just not opening.

A12X ipad pro 2018, iPadOS 16.6

**Comment by voidlovescats** [comment]
unplug your keyboard/mouse, it'll work

**Comment by KernelFox0** [comment]
> unplug your keyboard/mouse, it'll work

That's very weird, but it worked. Tha
